### ISSUE TITLE
[ Feature Request ] Levered Z-Switch Offset

### ISSUE THREAD

**Issue by wiggywoosaa** [protoloft/klipper_z_calibration#96]
*** UPDATE: Please delete this feature request, position_endstop, has the same effect. ***

Due to the VCORE unable to move out of the bed area, I have designed a z-switch (levered) that goes slightly over the bed.

The issue is there is a slight offset between when the switch is activated (Z0) and the bed.

Would it be possible to add a 'z-switch to bed' offset to bring z0 back to the bed.

Appologies if something like this already exists in some form, if it does please could you point me in the right direction.

TYIA

**Comment by TitusLabs** [comment]
The z end stop is never exactly level with the bed surface. That's why there is the z endstop position, which you need to calibrate: https://www.klipper3d.org/Manual_Level.html#calibrating-a-z-endstop

This plugin just automates that calibration. But you still need to get this z endstop position close to the bed surface to avoid getting a bigger offset from the auto-calibration - which is fine, but could more easily lead to trouble.
